name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu-amd64-dmg-sdl2:
    runs-on: ubuntu-latest
    steps:
    - name: apt update
      run: sudo apt update
    
    - name: install SDL
      run: sudo apt install libsdl2-dev

    - uses: actions/checkout@v4
    - name: make
      run: make CGB=0 sdl2
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: boyo-ubuntu-amd64-dmg-sdl2
        path: build/boyo
  build-ubuntu-amd64-cgb-sdl2:
    runs-on: ubuntu-latest
    steps:
    - name: apt update
      run: sudo apt update
    
    - name: install SDL
      run: sudo apt install libsdl2-dev

    - uses: actions/checkout@v4
    - name: make
      run: make CGB=1 sdl2

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: boyo-ubuntu-amd64-cgb-sdl2
        path: build/boyo
