name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-dmg:
    runs-on: ubuntu-latest
    steps:
    - name: apt update
      run: sudo apt update
    
    - name: install SDL
      run: sudo apt install libsdl2-dev

    - uses: actions/checkout@v4
    - name: make
      run: make
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gbemu-dmg
        path: gbemu
  build-cgb:
    runs-on: ubuntu-latest
    steps:
    - name: apt update
      run: sudo apt update
    
    - name: install SDL
      run: sudo apt install libsdl2-dev

    - uses: actions/checkout@v4
    - name: make
      run: make CGB=1

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gbemu-cgb
        path: gbemu
